INSERT INTO labels_table VALUES (1, "product_name")
INSERT INTO labels_table VALUES (2, "product_code" )
INSERT INTO labels_table VALUES (3, "quantity")
INSERT INTO labels_table VALUES (4,"scale" )
INSERT INTO labels_table VALUES (5, "pre_tare_weight")
INSERT INTO labels_table VALUES (6, "high_limit_pcs"  )
INSERT INTO labels_table VALUES (7, "unit_weight"  )
INSERT INTO labels_table VALUES (8, "low_limit_pcs"  )
INSERT INTO labels_table VALUES (9, "high_limit_kg"  )
INSERT INTO labels_table VALUES (10,"target_weight"  )
INSERT INTO labels_table VALUES (11,"low_limit_kg" )
INSERT INTO labels_table VALUES (12,"customer_name"  )
INSERT INTO labels_table VALUES (13, "customer_code")
INSERT INTO labels_table VALUES (14, "custom_field1"  )
INSERT INTO labels_table VALUES (15, "custom_field2"  )
INSERT INTO labels_table VALUES (16, "date_time" )
INSERT INTO labels_table VALUES (17, "ingredient_name")
INSERT INTO labels_table VALUES (18, "ingredient_code")
INSERT INTO labels_table VALUES (19, "ingredient_type")
INSERT INTO labels_table VALUES (20, "formula_name")
INSERT INTO labels_table VALUES (21, "formula_code")
INSERT INTO labels_table VALUES (22,"formula_type")
INSERT INTO labels_table VALUES (23, "length")
INSERT INTO labels_table VALUES (24,"width")
INSERT INTO labels_table VALUES (25,"height")
INSERT INTO labels_table VALUES (26, "distance_unit")
INSERT INTO labels_table VALUES (27, "weight_unit")
INSERT INTO labels_table VALUES (28, "vol_weight_surface")
INSERT INTO labels_table VALUES (29, "vol_weight_air")
INSERT INTO labels_table VALUES (30, "terminal_id")
INSERT INTO labels_table VALUES (31, "wt_adc")
INSERT INTO labels_table VALUES (32, "wt_conv")
INSERT INTO labels_table VALUES (33, "wt_offset")
INSERT INTO labels_table VALUES (34, "wt_span")
INSERT INTO labels_table VALUES (35, "wt_span_adc")
INSERT INTO labels_table VALUES (36, "wt_zero")
INSERT INTO labels_table VALUES (37, "wt_zero_adc")
INSERT INTO labels_table VALUES (38, "l_value")
INSERT INTO labels_table VALUES (39, "l_conv" )
INSERT INTO labels_table VALUES (40, "l_offset")
INSERT INTO labels_table VALUES (41,"l_span")
INSERT INTO labels_table VALUES (42,"l_span_adc")
INSERT INTO labels_table VALUES (43,"l_zero")
INSERT INTO labels_table VALUES (44,"l_zero_adc")
INSERT INTO labels_table VALUES (45,"w_value")
INSERT INTO labels_table VALUES (46,"w_conv")
INSERT INTO labels_table VALUES (47,"w_offset")
INSERT INTO labels_table VALUES (48,"w_span")
INSERT INTO labels_table VALUES (49,"w_span_adc")
INSERT INTO labels_table VALUES (50,"w_zero") 
INSERT INTO labels_table VALUES (51,"w_zero_adc")
INSERT INTO labels_table VALUES (52,"h_value")
INSERT INTO labels_table VALUES (53,"h_conv")
INSERT INTO labels_table VALUES (54,"h_offset")
INSERT INTO labels_table VALUES (55,"h_span")   
INSERT INTO labels_table VALUES (56,"h_span_adc") 
INSERT INTO labels_table VALUES (57,"h_zero")
INSERT INTO labels_table VALUES (58,"h_zero_adc")
INSERT INTO labels_table VALUES (59,"t_id")
INSERT INTO labels_table VALUES (60,"h_offset")
INSERT INTO labels_table VALUES (61,"h_span")  
INSERT INTO labels_table VALUES (62,"wt_capacity") 
INSERT INTO labels_table VALUES (63,"dst_unit")
INSERT INTO labels_table VALUES (64,"dst_res")
INSERT INTO labels_table VALUES (65,"wt_unit")
INSERT INTO labels_table VALUES (66, "wt_res")
INSERT INTO labels_table VALUES (67,"v_factor_air")  
INSERT INTO labels_table VALUES (68, "v_factor_surface")  

INSERT INTO units_table VALUES (1, "kg")
INSERT INTO units_table VALUES (2, "mg")
INSERT INTO units_table VALUES (3, "pcs")
INSERT INTO units_table VALUES (4, "g")